Pass dynamic client through to helm controller
coreos/lostromos pull request #1
Opened 2018-01-18 22:38 UTC by chancez

Needed for later changes which involve updating the CR status, and
querying the Kubernetes API directly, for when we need to check the
uncached version of a resource.

2018-01-18 22:43 UTC, ecordell requested changes
Can you thread the client into the other controllers as well?

2018-01-18 22:45 UTC, chancez commented
@ecordell I wasn't sure if it was going to be needed since they might not need it, and I'm not sure if we were planning on doing that for the go template controller.

The print controller almost certainly doesn't need it, does it?

2018-01-18 23:03 UTC, chancez commented
Added to the template controller. Do we need it in the printer as well?

2018-01-19 16:23 UTC, ecordell requested changes

2018-01-19 16:23 UTC, ecordell commented on cmd/start.go
> +func getController(dynClient *dynamic.Client, k8sClient kubernetes.Interface) crwatcher.ResourceController {
shouldn't this be dynamic.Interface?

2018-01-19 16:23 UTC, ecordell commented on crwatcher/watcher.go
> +func NewCRWatcher(cfg *Config, dc *dynamic.Client, rc ResourceController, l ErrorLogger) (*CRWatcher, error) {
ditto

2018-01-19 16:23 UTC, ecordell commented on tmplctlr/controller.go
> +func NewController(tmplDir string, kubeCfg string, logger *zap.SugaredLogger, kubeClient *dynamic.Client) *Controller {
ditto

2018-01-19 16:29 UTC, chancez commented
@ecordell Updated, will squash commit if it looks good.

2018-01-19 16:32 UTC, ecordell approved these changes
LGTM

2018-01-19 16:34 UTC, merged